When you create a Micronaut Framework application (either via https://launch.micronaut.io or the command line application), it creates a https://docs.micronaut.io/latest/api/io/micronaut/context/annotation/ContextConfigurer.html[ContextConfigurer] with enables https://docs.micronaut.io/latest/guide/index.html#eagerInit[eager singleton initialization].

As tests annotated with `@MicronautTest` are implicitly in the `Singleton` scope, this can cause problems injecting some beans (for example an `HttpClient`) into your test class.

To avoid this, you can either disable eager singleton initialization for your tests, or you will need to manually get an instance of the bean you would normally inject.  As an example, to get an `HttpClient` you could do:

[source,groovy]
.Getting an HttpClient instance in Spock with eager singleton initialization enabled
----
include::crac/src/test/groovy/io/micronaut/crac/EagerInitialisationSpec.groovy[tags=eager, indent=0]
----

<1> Inject the `EmbeddedServer` as normal
<2> Create a memoized method to create the `HttpClient` when it is first called
<3> Use the method to get the `HttpClient` and make the request
