plugins {
    id("io.micronaut.build.internal.crac-base")
    id("org.sonatype.gradle.plugins.scan")
}
String ossIndexUsername = System.getenv("OSS_INDEX_USERNAME") ?: project.properties["ossIndexUsername"]
String ossIndexPassword = System.getenv("OSS_INDEX_PASSWORD") ?: project.properties["ossIndexPassword"]
boolean sonatypePluginConfigured = ossIndexUsername != null && ossIndexPassword != null
if (sonatypePluginConfigured) {
    ossIndexAudit {
        username = ossIndexUsername
        password = ossIndexPassword
    }
}


dependencies {
    api(libs.managed.crac)
    compileOnly(mn.micronaut.http.server.netty)
    compileOnly(mnSql.micronaut.jdbc.hikari)
    compileOnly(mnData.micronaut.data.connection.jdbc)
    compileOnly(mnRedis.micronaut.redis.lettuce)
    compileOnly(mn.micronaut.management)

    testImplementation(mnData.micronaut.data.connection.jdbc)
    testImplementation(mnData.micronaut.data.tx)
    testImplementation(mnSql.micronaut.jdbc.hikari)
    testImplementation(mnSerde.micronaut.serde.jackson)
    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(mn.micronaut.http.client)
    testImplementation(mn.groovy.sql)
    testImplementation(mnLogging.logback.classic)

    testRuntimeOnly(mn.micronaut.management)
    testRuntimeOnly(mnSql.h2)
}
