[versions]
micronaut = "3.7.0"
micronaut-docs = "2.0.0"
micronaut-test = "3.6.2"
groovy = "3.0.13"
spock = "2.1-groovy-3.0"

managed-crac = "0.1.3"

[libraries]
managed-crac = { module = "io.github.crac:org-crac", version.ref = "managed-crac" }
