[versions]
micronaut = "4.0.0"

micronaut-cache = "4.0.1"
micronaut-data = "4.0.1"
micronaut-docs = "2.0.0"
micronaut-redis = "6.0.0"
micronaut-serialization = "2.0.0"
micronaut-sql = "5.0.1"
micronaut-test = "4.0.0"

groovy = "4.0.13"
spock = "2.3-groovy-4.0"

managed-crac = "1.3.0"

micronaut-logging = "1.0.0"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

micronaut-cache = { module = "io.micronaut.cache:micronaut-cache-bom", version.ref = "micronaut-cache" }
micronaut-data = { module = "io.micronaut.data:micronaut-data-bom", version.ref = "micronaut-data" }
micronaut-redis = { module = "io.micronaut.redis:micronaut-redis-bom", version.ref = "micronaut-redis" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serialization" }
micronaut-sql = { module = "io.micronaut.sql:micronaut-sql-bom", version.ref = "micronaut-sql" }

managed-crac = { module = "org.crac:crac", version.ref = "managed-crac" }

