[versions]
micronaut = "4.0.0-M2"

micronaut-cache = "4.0.0-M1"
micronaut-data = "4.0.0-SNAPSHOT"
micronaut-docs = "2.0.0"
micronaut-redis = "6.0.0-M2"
micronaut-serialization = "2.0.0-M3"
micronaut-sql = "5.0.0-M3"
micronaut-test = "4.0.0-M2"

groovy = "4.0.11"
spock = "2.3-groovy-4.0"

managed-crac = "0.1.3"

[libraries]
micronaut-cache = { module = "io.micronaut.cache:micronaut-cache-bom", version.ref = "micronaut-cache" }
micronaut-data = { module = "io.micronaut.data:micronaut-data-bom", version.ref = "micronaut-data" }
micronaut-redis = { module = "io.micronaut.redis:micronaut-redis-bom", version.ref = "micronaut-redis" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serialization" }
micronaut-sql = { module = "io.micronaut.sql:micronaut-sql-bom", version.ref = "micronaut-sql" }

managed-crac = { module = "io.github.crac:org-crac", version.ref = "managed-crac" }

