[versions]
micronaut = "4.0.0-SNAPSHOT"
micronaut-docs = "2.0.0"
spock = "2.1-groovy-3.0"
micronaut-test = "3.7.0"
groovy = "4.0.6"

managed-crac = "0.1.3"

[libraries]
managed-crac = { module = "io.github.crac:org-crac", version.ref = "managed-crac" }
