[versions]
micronaut = "3.8.6"
micronaut-docs = "2.0.0"
micronaut-test = "3.9.1"
groovy = "3.0.13"
spock = "2.3-groovy-3.0"

managed-crac = "1.3.0"

[libraries]

managed-crac = { module = "org.crac:crac", version.ref = "managed-crac" }
