package io.micronaut.crac.docs;

import io.micronaut.context.ApplicationContextBuilder;
import io.micronaut.context.ApplicationContextConfigurer;
import io.micronaut.context.annotation.ContextConfigurer;

/**
 * Enables eager singleton initialization for the Python test suite, like the {@code ContextConfigurer}
 * generated by <a href="https://launch.micronaut.io">Micronaut Launch</a>. The Java, Kotlin and Groovy
 * suites do the same per test with {@code @MicronautTest(contextBuilder = ...)}: Micronaut Test instantiates that
 * builder class reflectively before any application context (and with it the GraalPy runtime) exists, so it cannot
 * be a Python subclass of {@code DefaultApplicationContextBuilder}.
 */
@ContextConfigurer
public class EagerSingletonsConfigurer implements ApplicationContextConfigurer {

    @Override
    public void configure(ApplicationContextBuilder builder) {
        builder.eagerInitSingletons(true);
    }
}
